FROM ubuntu:22.04

LABEL maintainer="Valentin Goupille"

# Set R version
ARG R_VERSION=4.4.0
ENV R_VERSION=$R_VERSION

# Setting the Python version
ARG PYTHON_VER=3.10
ENV PYTHON_VER=$PYTHON_VER
ARG VENV_NAME="env_radian"
ENV VENV_NAME=$VENV_NAME
ARG QUARTO_VERSION=1.5.43
ENV QUARTO_VERSION=$QUARTO_VERSION
ARG MINICONDA_VERSION=py310_23.11.0-2
ENV MINICONDA_VERSION=$MINICONDA_VERSION
ENV TZ=UTC
ENV DEBIAN_FRONTEND=noninteractive
ENV CONFIGURE_OPTIONS="--with-cairo --with-jpeglib --enable-R-shlib --with-blas --with-lapack"

# Mirror
ARG CRAN_MIRROR=https://cran.rstudio.com/
ENV CRAN_MIRROR=$CRAN_MIRROR

#Bioconductor Mirror
ARG BIOCONDUCTOR_MIRROR=https://bioconductor.org/packages/release/bioc/
ENV BIOCONDUCTOR_MIRROR=$BIOCONDUCTOR_MIRROR
ENV BIOCONDUCTOR_VERSION=3.20
ENV BIOCONDUCTOR_SOFTWARE=${BIOCONDUCTOR_MIRROR}/bioc
ENV BIOCONDUCTOR_ANNOTATION=${BIOCONDUCTOR_MIRROR}/data/annotation
ENV BIOCONDUCTOR_EXPERIMENT=${BIOCONDUCTOR_MIRROR}/data/experiment

# Radian Settings
ENV R_PROFILE_USER="/root/.Rprofile"
ENV TERM_PROGRAM="vscode"
ENV VSCODE_INIT_R="R/session/init.R"

# Create a directory for packages builds
RUN mkdir -p pkgs

# Copy all necessary files
COPY docker/setting_files/* pkgs/

# Install Debian dependencies
RUN chmod +x pkgs/install_debian.sh && \
    bash pkgs/install_debian.sh

# Installing R
RUN R_VERSION_MAJOR=$(echo $R_VERSION | cut -d. -f1) && \
    R_VERSION_MINOR=$(echo $R_VERSION | cut -d. -f2) && \
    R_VERSION_PATCH=$(echo $R_VERSION | cut -d. -f3) && \
    wget https://cran.rstudio.com/src/base/R-${R_VERSION_MAJOR}/R-${R_VERSION}.tar.gz && \
    tar zxvf R-${R_VERSION}.tar.gz && \
    rm R-${R_VERSION}.tar.gz

WORKDIR /R-${R_VERSION}

RUN ./configure ${CONFIGURE_OPTIONS} && \
    make && \
    make install

RUN locale-gen en_US.UTF-8

WORKDIR /

# Install Miniconda
RUN chmod +x pkgs/install_miniconda.sh && \
    bash pkgs/install_miniconda.sh $MINICONDA_VERSION

ENV PATH=/opt/conda/bin:$PATH

# Create Conda environment
RUN chmod +x pkgs/create_conda_env.sh && \
    bash pkgs/create_conda_env.sh

# Install JupyterLab and configure env_1 for Python and IRkernel for my_env_R
RUN chmod +x pkgs/config_jupyter.sh && \
    bash pkgs/config_jupyter.sh

RUN chmod +x pkgs/install_python.sh && \
    bash pkgs/install_python.sh $VENV_NAME

RUN chmod +x pkgs/install_quarto.sh && \
    bash pkgs/install_quarto.sh $QUARTO_VERSION

# Install R packages
RUN mv pkgs/packages_vscode.json pkgs/packages.json && \
    Rscript pkgs/install_packages.R

# Clean up
RUN rm -rf pkgs/*

COPY docker/setting_files/.Rprofile /root/
RUN echo "alias r='radian'" >> ~/.bashrc

# Minimal JupyterLab configuration for Docker and Singularity
RUN mkdir -p ~/.jupyter && \
    echo "c.NotebookApp.ip = '0.0.0.0'" >> ~/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.port = 8888" >> ~/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.open_browser = False" >> ~/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.allow_root = True" >> ~/.jupyter/jupyter_notebook_config.py


